import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      className: 'nav-icon-home',
      collapsed: false,
      items: [
        'guide/intro/overview',
        'guide/intro/getting-started',
        'guide/intro/server-configuration',
        'guide/intro/key-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      className: 'nav-icon-functions',
      items: ['guide/functions/working-with-functions'],
    },
    {
      type: 'category',
      label: 'Publishers',
      className: 'nav-icon-publishers',
      items: [
        'guide/publishers/index',
        {type: 'autogenerated', dirName: 'guide/publishers'},
      ],
    },
    {
      type: 'category',
      label: 'Transformers',
      className: 'nav-icon-transformers',
      items: ['guide/transformers/working-with-transformers'],
    },
    {
      type: 'category',
      label: 'Subscribers',
      className: 'nav-icon-subscribers',
      items: [
        'guide/subscribers/index',
        {type: 'autogenerated', dirName: 'guide/subscribers'},
      ],
    },
    {
      type: 'category',
      label: 'Kafka',
      className: 'nav-icon-kafka',
      items: ['guide/kafka/working-with-kafka'],
    },
    {
      type: 'category',
      label: 'Triggers',
      className: 'nav-icon-triggers',
      items: ['guide/triggers/working-with-triggers'],
    },
    {
      type: 'category',
      label: 'Tables',
      className: 'nav-icon-tables',
      items: [{type: 'autogenerated', dirName: 'guide/tables'}],
    },
    {
      type: 'category',
      label: 'Plugins',
      className: 'nav-icon-plugins',
      items: ['guide/plugins/working-with-connector-plugins'],
    },
    {
      type: 'category',
      label: 'Data Quality',
      className: 'nav-icon-dataquality',
      items: ['guide/data-quality/data-quality'],
    },
    {
      type: 'category',
      label: 'Catalogs',
      className: 'nav-icon-catalogs',
      items: [
        'guide/catalogs/index',
        'guide/catalogs/aws-glue',
        'guide/catalogs/unity-catalog',
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      className: 'nav-icon-platform',
      items: [
        'guide/platform/user-interface',
        'guide/platform/ai-agent',
        {
          type: 'category',
          label: 'Secrets Management',
          items: [
            'guide/platform/secrets-management/index',
            'guide/platform/secrets-management/env-variables',
            'guide/platform/secrets-management/hashicorp',
          ],
        },
        'guide/platform/permissioning',
        'guide/platform/security',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      className: 'nav-icon-operations',
      items: [
        'guide/operations/testing',
        'guide/operations/troubleshooting',
        'guide/operations/cli-commands',
        'guide/operations/release-notes',
        'guide/operations/contact-support',
      ],
    },
  ],

  tutorialsSidebar: [
    {type: 'autogenerated', dirName: 'tutorials'},
  ],

  apiSidebar: [
    'api/alphabetical-index',
    {
      type: 'category',
      label: 'By Category',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'api/category'}],
    },
    {
      type: 'category',
      label: 'By Module',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'api/module'}],
    },
  ],
};

export default sidebars;
